language: node_js
node_js:
  - "node"
install:
  - npm install
script: 
- ng build --prod --base-href https://92denis.github.io/rcs/
branches:
only:
    - master
deploy:
  local_dir: ./dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
